### ISSUE TITLE
reference-bisulfitation requires reference fasta to have .fa ending

### ISSUE THREAD

**Issue by cschu** [sing-group/bicycle#1]
It should at least allow .fasta and maybe .fna. The worst part is that it just silently does nothing instead of at least issuing a warning.

**Comment by lipido** [comment]
Thank you for reporting this. We have added support for .fna and .fasta in commit 542c72fdfac6a1a0fcfa22009f882d7945b714e2 which is in the branch "develop" and is planned for the next 1.9.0 release.

You can download the 1.9.0-SNAPSHOT from the develop branch if you want to work with a version including this enhancement.

**Comment by cschu** [comment]
Cheers, for now I have just used a .fa-softlink, but that will be handy for potential future applications!
