### ISSUE TITLE
q-value doesnt change across methylated regions

### ISSUE THREAD

**Issue by freedomq8** [sing-group/bicycle#6]
Hi there, 

I manage to get perform the differential methylation analysis along with the bed file. However, when I get the results of q-value its the same across the whole methylated regions unlike p-value. 

Example
`
#region | sequence | start | stop | T3 (treatment) | T3R (treatment) | T1 (control) | T1R (control) | treatment average | control average | log2FC(treament/control) | p-value | q-value
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr1_217308838-217309329 | chr1 | 2.17E+08 | 2.17E+08 | 139/882 | 213/1379 | 67/1191 | 24/734 | 0.155683 | 0.047273 | 1.719534 | 4.85E-04 | 0.80766
chr4_174443205-174444459 | chr4 | 1.74E+08 | 1.74E+08 | 426/1676 | 479/1942 | 393/2444 | 305/1989 | 0.250138 | 0.157455 | 0.667782 | 4.96E-04 | 0.80766
chr11_123172361-123173273 | chr11 | 1.23E+08 | 1.23E+08 | 251/1162 | 349/1695 | 570/1828 | 508/1495 | 0.210011 | 0.324406 | -0.62734 | 5.33E-04 | 0.80766
chr3_61548855-61549505 | chr3 | 61548855 | 61549505 | 162/343 | 223/468 | 326/474 | 424/633 | 0.474723 | 0.677507 | -0.51315 | 8.71E-04 | 0.80766
chr17_40575129-40575502 | chr17 | 40575129 | 40575502 | 16/276 | 22/279 | 55/233 | 73/234 | 0.068468 | 0.27409 | -2.00114 | 8.93E-04 | 0.80766
`

> 
This same happened with different comparison of samples. but with different fixed value.
 the command I used
`
bicycle analyze-differential-methylation -p /mnt/BAM/Group5/Table5 -c 9269E,9270E,9272E -t 9271E,9362E,9363E,9364E -b /mnt/reference/hg19/truseq-methyl-capture-epic-manifest-file.bed
`

Any suggestion ?

Update: it does change but another fixed value, so in each analysis I will have 2 or 3 q-value. Just wanted to know if this is normal/correct.

**Comment by lipido** [comment]
How many lines do you have in the p-values file?

**Comment by lipido** [comment]
In any case, it is possible to get repeated qvalues. For example, if you try with R, with only the p-values you showed in the table, you will also get repeated q-values:

```
p.adjust(c(4.85E-04 , 4.96E-04, 5.33E-04,  8.71E-04, 8.93E-04), method = "fdr")
[1] 0.0008883333 0.0008883333 0.0008883333 0.0008930000 0.0008930000
```

**Comment by freedomq8** [comment]
I have 9 comparisons/analysis and usually I do have q-values, so just wanted to know if this is normal or not. it could be just my data or the biological questions we are asking. Since I don't have something significant in any of these comparisons, I would be more interested in the multi-testing correction method used. As well as the current p-value column is that the unadjusted p value ? also can I include covariate in the analysis which might help the p&q values? Also I would be interested if there are other correction for methods i.e Bonferroni , FDR (Up and Down). 


Thanks a lot

**Comment by lipido** [comment]
These q-values may be absolutely normal.

Yes, the p-value column is the unadjusted p-value.

By now, bicycle does not support neighter covariates in the analysis nor other multiple testing corrections.

**Comment by freedomq8** [comment]
Thanks for the clarification
